### ISSUE TITLE
Mod Crashes On Server Looking For Server Proxy Class

### ISSUE THREAD

**Issue by TeetoKaziim** [FoxMcloud5655/Draconic-Additions#1]
<https://gist.github.com/TeetoKaziim/617a9783e1e14c3eed55cf27dba16bd2>

Launches just fine in singleplayer, has trouble on forge server.

Forge: 2815
Draconic Additions: 1.1.1.3

218 other mods.

**Comment by FoxMcloud5655** [comment]
I see.  I don't use the server class at all, hence why it was not included.  Apparently, I need to do more research!  Thanks for bringing this up.
