### ISSUE TITLE
Add ru_RU.lang to the addon.

### ISSUE THREAD

**Issue by Lewui** [FoxMcloud5655/Draconic-Additions#11]
Hello, im translate the addon.
[ru_RU.txt](https://github.com/FoxMcloud5655/Draconic-Additions/files/3526275/ru_RU.txt)

**Comment by FoxMcloud5655** [comment]
Nice job!  At least, I'm assuming, since I can't read Russian.  There is one entry that I think you missed?  Chaos Container explosion text, I believe.

**Comment by Lewui** [comment]
> Nice job! At least, I'm assuming, since I can't read Russian. There is one entry that I think you missed? Chaos Container explosion text, I believe.

I got mistake in "config.field.shirtEntropyActivate.description" text i think

**Comment by Lewui** [comment]
And i forgot change chaos container explode text, one minute and this done

**Comment by Lewui** [comment]
[ru_RU.txt](https://github.com/FoxMcloud5655/Draconic-Additions/files/3526409/ru_RU.txt)
This is translate with changed chaos container explode
