### ISSUE TITLE
Overload Crash

### ISSUE THREAD

**Issue by MineplayerHDYT** [FoxMcloud5655/Draconic-Additions#12]
https://paste.dimdev.org/widiwocare.mccrash

**Comment by FoxMcloud5655** [comment]
Looks like your version of Draconic Evolution is out of date.

**Comment by MineplayerHDYT** [comment]
Yeah that could be true haha

**Comment by MineplayerHDYT** [comment]
What does the Baubles Item's do?

**Comment by FoxMcloud5655** [comment]
If you need info about items in my mod, check Project Intelligence.
