### ISSUE TITLE
Armor not custom

### ISSUE THREAD

**Issue by epeeforteyt** [FoxMcloud5655/Draconic-Additions#13]
Hello, I can not configure the armor of your mod, the craft system is excellent, but impossible to adjust the parameters, Also Staff can not break any block, even a simple stone, See for yourself =>

http://bit.ly/2pCUpGk

Forge: 14.23.5.2847
MC/ 1.12.2
Mod: Draconic-Additions-1.12.2-1.8.2.25-universal.jar 
Mod: Draconic-Evolution-1.12.2-2.3.24.349-universal.jar

**Comment by FoxMcloud5655** [comment]
Have you tried looking at the item in Project Intelligence?  You must stabilize all Chaotic gear before it's useful.

**Comment by epeeforteyt** [comment]
How should the armor be stable O_o

Wiki ?

**Comment by FoxMcloud5655** [comment]
Again, have you tried looking at the item in Project Intelligence?

**Comment by epeeforteyt** [comment]
Thx - Chaos Armor <3
