### ISSUE TITLE
Chaos Block - Energy Core

### ISSUE THREAD

**Issue by epeeforteyt** [FoxMcloud5655/Draconic-Additions#14]
Hello, this is not a problem but a request for the Draconic ball, if it would be possible to have a tier 9 in Chaos Block to store the energy in, a black of darkness, thank you very much for having does this beautiful mod.

**Comment by FoxMcloud5655** [comment]
You know, I have already given the idea some thought, but I realized that in a typical playthrough, even a tier 7 energy core is WAY more than enough to store power for all of your devices.

I'll leave this issue open while I think about it, but if I do implement this, don't expect it to be easy to build or maintain.  Chaos isn't meant to be easy to control!

**Comment by epeeforteyt** [comment]
Thank you, yes I suspect it will not be easy to create or stabilized. But I would take up the challenge =)

**Comment by FoxMcloud5655** [comment]
I've decided that this is not necessary.  However, if you can prove that you actually need more storage for a single operation (no matter how long it might take) than the Tier 8 Draconic Energy Core can store, then I will reopen the issue and conciser making it again.

**Comment by FoxMcloud5655** [comment]
I have also decided to make something based off of this idea, though, so don't think your idea is going out the window!

**Comment by epeeforteyt** [comment]
Ok thank you, look forward to seeing your new idea :)
