### ISSUE TITLE
[BUG] 1.12.2 Tools and Armor dont work propely!

### ISSUE THREAD

**Issue by NikeSchuh** [FoxMcloud5655/Draconic-Additions#15]
Version : 1.12.2
Forge : 14.23.5.2847
Server / Multiplayer : Yes (Is in singleplayer too)

Description : 
- Potato armor isnt craftable

**Comment by Lewui** [comment]
You need to stabilise the armour and staff before configure this

**Comment by NikeSchuh** [comment]
Thank you! :D
