### ISSUE TITLE
[Chaotic Staff] Attack Radius doesn't work

### ISSUE THREAD

**Issue by NikeSchuh** [FoxMcloud5655/Draconic-Additions#16]
Putting the Attack Radius on 0 changes nothing. The staff still attacks Mobs and Players in a 8 Block Radius.

**Comment by FoxMcloud5655** [comment]
Is the staff stabilized or not?  This is intentional if you haven't used the stabilization ritual.

**Comment by NikeSchuh** [comment]
Yes it is stabelized

**Comment by FoxMcloud5655** [comment]
Upon further testing, this is indeed a bug.  Thanks for reporting, and I'll get on it right away.
