### ISSUE TITLE
[Potato Armor] Is not craftable!

### ISSUE THREAD

**Issue by NikeSchuh** [FoxMcloud5655/Draconic-Additions#17]
MC : 1,12,2
Multiplayer : Yes
Version : Draconic-Additions-1.12.2-1.9.1.27-universal.jar
Issue : Crafting Energized Potato Armor still isnt possible since the first release of the mod!

Error : https://hastebin.com/usizolumes.rb

**Comment by FoxMcloud5655** [comment]
It's working just fine for me.  It must be your configuration.  What version of Forge are you using?

**Comment by NikeSchuh** [comment]
I am using Forge 14.23.5.2847

**Comment by FoxMcloud5655** [comment]
I see no problems at all with any of my testing I just finished performing with many different Forge versions.

It might be a deeper issue than my mod...  Why don't you post the list of mods you're using?  It sounds like everything on your end works up until the transformation point, at which it's saying that there is no method to determine what piece of armor it is (leggings, boots, etc.)

**Comment by NikeSchuh** [comment]
All my mods:
AbyssalCraft
AbyssalCraft Intergration
Actually Additions
Advanced Solar Panels
Anvilpatch
Applied Energistics 2
Aquaculture
ArmorPlus
Astral Sorcery
Avaritia 1.1x
Baubles
Baubles Hud
Bewitchment
Blood Magic
Blood Moon
Bookshelf
Botania
Botanic Additions
Bountiful Baubles
Brandons Core
Chisel
CodeChickenLib
CoFHCore
CoFHWorld
Conarm
CTM
Cucumber
Cyclic
DarkUtils
Draconic Additions
Draconic Evolution
Ender Core
EnderIO
Environmentalmaterials
Environmentaltech
Extra Botany
Extra Utilities 2
Extreme Reactors
Forgelin
Guide API
Hammer Core
Immersive Engineering
Industrial Craft 2
Inventory Pets
Just Enough Items
Journey Map
Librarian Lib
Mantle
Mcjtylib
Mekanism
Mekanism Tools
Mystical Agradditions
Mystical Agriculture
Natural Pledge
Open Blocks
OpenModsLib
Patchouli
Progressive Bosses
Project E
Project EX
Redstone Flux
Rftools
Rftools Dimensions
TConstruct
TheDragonLib
Thermal Dynamics
Thermal Expansion
Thermal Fundation
Thut Wearables
Tinker's JEI
TinkerToolLeveling
Valkyrielib
Wizardry
Zerocore

**Comment by FoxMcloud5655** [comment]
I've just downloaded every mod you have and ran my client with the same forge version.  Everything works exactly as expected.

Would you mind taking a video of it happening so I can see exactly at what point it's failing on your machine?

**Comment by FoxMcloud5655** [comment]
Also, your "hastebin" has been deleted.  Please post up the original text directly here for archival purposes.

**Comment by NikeSchuh** [comment]
Ok , I will post the error and a Video soon.

**Comment by NikeSchuh** [comment]
Have you tested it on a server? Or in singleplayer? In singleplayer it works fine.

**Comment by FoxMcloud5655** [comment]
That's a good guess.  I'll test it next time I get access to my computer.

**Comment by NikeSchuh** [comment]
I cant go to my Computer Right now that's why i cant post the error Right now. Im sorry.

**Comment by FoxMcloud5655** [comment]
Closing due to age.
