### ISSUE TITLE
[Suggestion] Amulet's and Ring's

### ISSUE THREAD

**Issue by NikeSchuh** [FoxMcloud5655/Draconic-Additions#18]
Draconic Undershirt of Self-Siphoning:
Should give more Shield for the trade of a heart.

Draconic Belt of Overloading:
It is to weak for the price of the Shield you charge into it.

Shielding Necklaces:
They are way to weak for example the best amulet you can get costs 5 nether stars and gives you as much Shield as the potato armor which costs 0 nether stars.

It would be cool if all are upgradeable.

Thanks for the cool extension! 👍

**Comment by FoxMcloud5655** [comment]
Let me go over each of these one by one.

Draconic Undershirt of Self-Siphoning:
This does not give you shielding.  This reduces the amount of entropy at the cost of HP.  It's supposed to help, not be OP!

Draconic Belt of Overloading:
Are you sure about that?  Have you tried using it in bursts and decimating literally anything with your sword or staff?  Using it right, you can literally one shot the Ender Dragon.

Shielding Necklaces:
Here's the thing; Necklaces of Shielding are very efficient in terms of RF usage.  They are also permanent, unlike Potato Armor whose RF cannot be recharged by default.  Finally, they are balanced to fit how I view DE should be played; with all armors only giving 1/4 of what they normally do.

If you dislike how my items work, you can always rebalence them yourself by modifying the parameters in "Mod Options", then searching for "Draconic Additions".
