### ISSUE TITLE
[Chaotic Armor] Strange Upgrading

### ISSUE THREAD

**Issue by NikeSchuh** [FoxMcloud5655/Draconic-Additions#19]
Minecraft : 1.12.2
Forge : 14.23.5.2847

When upgrading a draconic armor without any Upgrades to the chaotic Tier all Upgrades will be set to the draconic Tier without even having to upgrade them.

**Comment by FoxMcloud5655** [comment]
I just tried to upgrade a Draconic Chestplate with nothing on it, and it came out as a Chaotic Chestplate with one basic RF upgrade applied to it.  This is an odd bug...  It may not be related to my mod, but to Draconic Evolution itself.

**Comment by FoxMcloud5655** [comment]
After investigation, my initial thoughts are that this is a problem with how Draconic Evolution applies tool upgrades.  I will look into this further at a later date.

**Comment by FoxMcloud5655** [comment]
Appears not to have happened after the September 7th, 2020 update.  Closing for now.  If this issue appears again, please comment and I'll re-open it.
