### ISSUE TITLE
Infused Potato Armor void if in the first Hotbar slot when right-click

### ISSUE THREAD

**Issue by Fireztonez** [FoxMcloud5655/Draconic-Additions#2]
Hello,
I just install and test the infused Potato Armor, quetsion to get the Energized Potato Armor... It work if in every slot of the hotbar and right-click, but, if is in the first slot, for some strange reason the arnor is just deleted... I try about 20 times, and each time, it delete if is on the first slot...

Here a small Video-Clip of my test, during my live:
https://clips.twitch.tv/ExuberantCoyPeachDancingBanana

Thank's
Fireztonez

**Comment by Fireztonez** [comment]
Finally, the problem look even more strange, because somes time it work in the first slot, and somes time it void the armor when in other slot... I can't really understand what appen, this si really stange...

**Comment by FoxMcloud5655** [comment]
Huh.  That is really strange; I'll do some further testing.

**Comment by FoxMcloud5655** [comment]
In my testing with just Draconic Evolution, Draconic Additions, and it's dependencies, everything works just fine.
It's probably a cross-mod issue; would you mind providing your mod list or your `latest.log` from a session that you tried to use the armor and it failed?

**Comment by FoxMcloud5655** [comment]
In the meantime, I'll be pushing an update that might or might not fix the problem.

**Comment by Fireztonez** [comment]
I have the same issue with the latest version of Draconic Addition (v.1.3.0.7) and Draconic Evolution (v.2.3.20.333) in my modpack... I really don't know what mod can caused that issue, I can possibly look if I can fond something, but, here the current list of mod in the pack;
https://gist.github.com/Fireztonez/ec06af2a8d601223f0899432e51efc34

and here the part of the logs where I try to get somes armor parts, but I can't see really anything usefull... If you need something else, let me know (Is look to only work when it goes on a slot before the slot we have the part currently the infused armor part...):
https://gist.github.com/Fireztonez/9efdf9366cecc0dff1e622e98816f281

If you have any idea what mod can caused the issue on that list, let me know and I can try and see..

**Comment by FoxMcloud5655** [comment]
Looks pretty standard; I'm going to try downloading all of your mods and see if any of them are conflicting.

**Comment by Fireztonez** [comment]
Ok, thank you!

**Comment by Fireztonez** [comment]
Thank's everithing work's fine with the version 1.5.1.10, thank's!

I really like the idea of attacking a mob with armor pieces to empowered... You should add an option to be the only way to get-it empowered!!

Thank's again
Fireztonez

**Comment by FoxMcloud5655** [comment]
Great idea!  I'll include it in the next update.

**Comment by Fireztonez** [comment]
Nice!! Thank's a lot :D
