### ISSUE TITLE
Chaotic Chest Armor flight speed can't be changed from 600

### ISSUE THREAD

**Issue by Jaitsu** [FoxMcloud5655/Draconic-Additions#24]
When trying to change the chest armor's flight speed (after stabilizing it), the entire slider is "600%" with no way to increase or decrease it.

**Comment by Jaitsu** [comment]
Also, upon checking around: this also affects Jump Modifier on the boots. Speed Modifier on the leggings appears to be unaffected. (for what it's worth, I have Draconic upgrades on all armor pieces, but not Chaotic yet.)

**Comment by Jaitsu** [comment]
Evidently, those pieces of armor *weren't* stabilized, because after running them through the stabilizer again now they're behaving and I can change the sliders. (May need some flavor text or some indicator that they haven't been stabilized?)

**Comment by FoxMcloud5655** [comment]
In the latest version of Draconic Additions, there is flavor text indicating its current state.  Glad you found out they weren't stabilized.
