### ISSUE TITLE
Portable Draconic Charger: Wrong recipe?

### ISSUE THREAD

**Issue by TimeConqueror** [FoxMcloud5655/Draconic-Additions#25]
Hello!
As I understand, here should be an Awakened Core.
![image](https://user-images.githubusercontent.com/25156941/80308188-2a42e680-87d6-11ea-9c24-3bfea6bd3e30.png)

**Comment by FoxMcloud5655** [comment]
Unfortunately, I made this mistake when creating the recipe. I've already got it fixed in the development branch, and I'll be publishing and update today that fixes this.

**Comment by FoxMcloud5655** [comment]
Fixed in [14f6e4a](https://github.com/FoxMcloud5655/Draconic-Additions/commit/14f6e4a6c84ab1895fcf3de2ff5ddc58dffa5ca6).
