### ISSUE TITLE
Can't change chaotic chestplate flight speed

### ISSUE THREAD

**Issue by kill05** [FoxMcloud5655/Draconic-Additions#26]
When i first put the chaotic chestplate the speed boost is at 600% and can't be reduced. Is this intentional or is it a bug?
Also i can't change walking speed boost on leggings and jump boost on boots.

**Comment by FoxMcloud5655** [comment]
This is intentional.  Please use Project Intelligence to view the in-game documentation on the stabilization ritual.

**Comment by kill05** [comment]
ok, thanks!
