### ISSUE TITLE
Adding verification for the mod Baubble 

### ISSUE THREAD

**Issue by Fireztonez** [FoxMcloud5655/Draconic-Additions#3]
Hello,
I have try your mod in a clean modpack with only Draconic evolution and is dependencies + Draconic Additrions, and the game crash, but I finally found the caused, but this is really not clear into the crash log...

I finally found the problem, I have not install Bauble, so after I added everithing work, but I think, you should add a verification if the mod is installed before you used something from, Like that, it will probably add a clear error message Mod Missing and not only a Crash Logs, without really any clear information...

This is just a suggestion!
Draconic-Additions: 1.3.0.7 or 1.3.0.8 (I have try both...)

Fireztonez

**Comment by FoxMcloud5655** [comment]
Hmm.  I think my assumption that Draconic Evolution required Baubles as a dependency was incorrect.  I'll fix that right now.
