### ISSUE TITLE
this mod wont appear in sky factory 4

### ISSUE THREAD

**Issue by Noahfrechette** [FoxMcloud5655/Draconic-Additions#32]
this mod wont appear in sky factory 4 i chech the folder and it is there

**Comment by Noahfrechette** [comment]
i have brandon core and draconic evolution and this mod does not apear

**Comment by FoxMcloud5655** [comment]
Sky Factory 4 does not include Draconic Evolution by default, as far as I can see online.  Is this a customized pack?

**Comment by Noahfrechette** [comment]
yes i added it in the mods folder but u have draconic evolution and brandons core and it does not show

**Comment by Noahfrechette** [comment]
u is i

**Comment by Noahfrechette** [comment]
found the problem shows in jei but minecraft creative doesent

**Comment by Noahfrechette** [comment]
ok i reloded cursefroge beta and it is now showing

**Comment by Noahfrechette** [comment]
and closed minecraft and repoened
