### ISSUE TITLE
Game Crashes on launch

### ISSUE THREAD

**Issue by Rapture288** [FoxMcloud5655/Draconic-Additions#33]
Just tried installing draconic additions into my ftb revelations mod pack, are there any dependencies it has that are not included in rev?
bellow is the error log
[additionscrash.txt](https://github.com/FoxMcloud5655/Draconic-Additions/files/5720317/additionscrash.txt)

**Comment by FoxMcloud5655** [comment]
This is because your version of Draconic Evolution and Brandon's Core are out of date.  Might want to ensure those are up to date before trying to launch again.
