### ISSUE TITLE
Cant add energy to potato armor

### ISSUE THREAD

**Issue by MrBlyatWasTaken** [FoxMcloud5655/Draconic-Additions#34]
Version: 1.12.2
Issue: I can't charge the potato armor using draconic's charger or any other mod's charging solutions.

**Comment by FoxMcloud5655** [comment]
That is intended.  The Potato Armor comes with RF already built-in, and drains from that RF pool until low, then breaks, refunding some resources.

If you feel like this is wrong and want to change the intended behavior, everything about the Potato Armor is fully customizable in the config.  You don't even have to open up the file manually; it supports changing values in-game.
