### ISSUE TITLE
Crashing when added to FTB revelation

### ISSUE THREAD

**Issue by Silverwolf2332** [FoxMcloud5655/Draconic-Additions#36]
When added to the FTB revelations modpack it crashes on startup. There are a few mods that I have added due to the server that I play on. 
The mods that are added are VoicechatReloaded and debugServerInfo

[latest.log](https://github.com/FoxMcloud5655/Draconic-Additions/files/5963591/latest.log)

**Comment by FoxMcloud5655** [comment]
This is not a bug.  Your versions of Brandon's Core and Draconic Evolution are out of date.  Update your mods, and the problem will disappear.
