### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by remidu64** [FoxMcloud5655/Draconic-Additions#37]
when i install the mod, the mod brandon's core (used for draconic evolution) doesn't want to load and gets marked as "errored"
[crash-2021-02-27_21.08.37-client.txt](https://github.com/FoxMcloud5655/Draconic-Additions/files/6062174/crash-2021-02-27_21.08.37-client.txt)

**Comment by FoxMcloud5655** [comment]
You are getting this error because you have not updated your mods.  Update Brandon's Core and Draconic Evolution, and you won't have this issue anymore.
