### ISSUE TITLE
Chaotic Staff of Power

### ISSUE THREAD

**Issue by St0cKii** [FoxMcloud5655/Draconic-Additions#4]
Chaotic Staff of Power dont brake any blocks is more a downgrade then a upgrade...Can´t even configure the item

**Comment by FoxMcloud5655** [comment]
This is intentional.  Information about upgrading the staff is located in Project Intelligence, once it updates.

**Comment by FoxMcloud5655** [comment]
For now, let me give you a link to the multiblock setup.

http://foxmcloud.net/experiments/ChaosStabilizerMultiblock.png
