### ISSUE TITLE
Capacitor Supplier Energy Dupe

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [FoxMcloud5655/Draconic-Additions#40]
You are able to create infinity amounts of power when you connect two capacitors together with energy cables. The capacitors require two or more flux capacitors inside of them to do this. 

x2 (Or more) Capacitor Supplier
x2 (Or more) energy cables
x2 (or more) Flux Capacitors CHARGED
x1 Power Bank (Or anything else) (Best performed with a draconic energy ball tier 8)

Example
![image](https://user-images.githubusercontent.com/61563491/115925237-b97deb00-a478-11eb-80ca-422083b962f5.png)

**Comment by YouSeeMeRunning2** [comment]
High transfer cables such as cryo-stabilized fluxducts can be used to make full use of this

**Comment by FoxMcloud5655** [comment]
I see...  I've tested this out and this appears to be the case when 2 Capacitor Suppliers are next to each other.  I think this has something to do with a feedback loop when sending energy; I'll look into this.  Thank you for reporting.

**Comment by YouSeeMeRunning2** [comment]
> I see... I've tested this out and this appears to be the case when 2 Capacitor Suppliers are next to each other. I think this has something to do with a feedback loop when sending energy; I'll look into this. Thank you for reporting.

When will the jar be published?

**Comment by FoxMcloud5655** [comment]
I want to publish it right now, but as of 4/20/2021, Forge started to migrate their servers and because of this, my build isn't working properly since it attempts to request updates every build.

I either have to wait for Forge to finish their migration or find a way of forcing Gradle (the organizer program that builds DA) to use locally cached files.  I had taken a look at doing the latter yesterday, but ran out of time.

**Comment by runescapejon** [comment]
You could update to FG 4.+ and work with forge 1.12.2. However, if you still want to use FG 2.3 there a fork that I'd been using 
Here's the fork https://github.com/SizableShrimp/ForgeGradle/tree/FG_2.3

Maven that I used:
```
        mavenCentral()
        maven { url = 'https://sizableshrimp.me/maven' }
        maven { url = 'https://maven.minecraftforge.net/' }
```
You can use this to compile it.

**Comment by FoxMcloud5655** [comment]
Thanks, @runescapejon!  That ended up working for me.  I originally changed my URL to target `https://maven.minecraftforge.net/`, but it still wasn't working for me.  I didn't realize that the ForgeGradle script needed to be updated too.
