### ISSUE TITLE
Unable to Stabilizing Core

### ISSUE THREAD

**Issue by runescapejon** [FoxMcloud5655/Draconic-Additions#41]
Hello, I'm currently on `Draconic-Evolution-1.12.2-2.3.27.353-universal` and `Draconic-Additions-1.12.2-1.16.2.42-universal`
`BrandonsCore-1.12.2-2.4.19.214-universal` It seems that once I build the platform right click and throw the Chaotic Staff of Power didn't do anything, just a small increase of size in the Chaos Stabilizer Core no storm effect or any of it.
The structure that I build: https://gyazo.com/c686105e1c7d8db15c0738a97cfac638
and the video guide that used: https://www.youtube.com/watch?v=kgG43rO6dFQ

Of course, I check in the Project Intelligence mod for documentation in case I mess up.  I'm not sure if I'm doing something wrong here or it's a bug, thank you.

**Comment by FoxMcloud5655** [comment]
Everything on your end looks correct.  What is the message you get when you right-click the core with the staff in-hand?

**Comment by runescapejon** [comment]
Well, once I right-click with the staff in hand it displays no messages. However, if I attempt to right-click the staff in-hand again it will give an action bar message of `"The stabilizer remains inert. You've already stabilized this item."`

**Comment by FoxMcloud5655** [comment]
You're in creative mode.  Creative mode players can right-click an active stabilizer setup to instantly stabilize the item they're holding.

**Comment by runescapejon** [comment]
ah, I didn't realize there a difference in what game mode we are in. Thank you
