### ISSUE TITLE
Stabilizing the Semi-Stable Chaotic Crystal

### ISSUE THREAD

**Issue by DistortedAkino** [FoxMcloud5655/Draconic-Additions#42]
I have tried a few times only once getting a stabilized crystal back but it gave me the unstabilized crystal back too. I was expecting the storm thingy and it doing what the other things did when getting stabilized but nothing happens besides the core saying it rejects the object in my hand for stabilizing.

**Comment by SGZ-Creations** [comment]
Just wonder what is it's use ?

**Comment by FoxMcloud5655** [comment]
Decoration.
