### ISSUE TITLE
Minecraft crushes on launch

### ISSUE THREAD

**Issue by GuakeTheDragon** [FoxMcloud5655/Draconic-Additions#43]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2021-04-27 21:06:33 VLAT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Brandon's Core (brandonscore)
Caused by: java.lang.NoSuchMethodError: com.brandon3055.draconicevolution.client.creativetab.DETab.<init>(Ljava/lang/String;Ljava/lang/String;I)V
    at net.foxmcloud.draconicadditions.client.creativetab.DATab.<init>(DATab.java:19)
    at net.foxmcloud.draconicadditions.DAFeatures.<clinit>(DAFeatures.java:33)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at com.brandon3055.brandonscore.registry.ModFeatureParser.parseASMData(ModFeatureParser.java:76)
    at com.brandon3055.brandonscore.BrandonsCore.preInit(BrandonsCore.java:77)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_281, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1330678648 bytes (1269 MB) / 2818572288 bytes (2688 MB) up to 6442450944 bytes (6144 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 71 mods loaded, 71 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                     | Version         | Source                                             | Signature                                |
       |:----- |:---------------------- |:--------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft              | 1.12.2          | minecraft.jar                                      | None                                     |
       | LCH   | mcp                    | 9.42            | minecraft.jar                                      | None                                     |
       | LCH   | FML                    | 8.0.99.99       | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                  | 14.23.5.2854    | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | xaerominimap_core      | 1.12.2-1.0      | minecraft.jar                                      | None                                     |
       | LCH   | xaeroworldmap_core     | 1.12.2-1.0      | minecraft.jar                                      | None                                     |
       | LCH   | foamfixcore            | 7.7.4           | minecraft.jar                                      | None                                     |
       | LCH   | bspkrscore             | 7.6.0.1         | 1.12bspkrsCore_universal_7.6.0.1.jar               | None                                     |
       | LCH   | treecapitator          | 1.43.0          | 1.12TreeCapitator_client_1.43.0.jar                | None                                     |
       | LCH   | appliedenergistics2    | rv6-stable-7    | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCH   | baubles                | 1.5.2           | baubles-1.12-1.5.2.jar                             | None                                     |
       | LCH   | redstoneflux           | 2.1.1           | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
       | LCH   | tesla                  | 1.0.63          | Tesla-1.12.2-1.0.63.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | p455w0rdslib           | 2.3.161         | p455w0rdslib-1.12.2-2.3.161.jar                    | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCH   | ae2wtlib               | 1.0.34          | AE2WTLib-1.12.2-1.0.34.jar                         | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCH   | aoa3                   | 3.3.6           | AoA3_1.12.2_3.3.6.jar                              | 8bddeac148843f40e0b9f69201be2f4b3071700d |
       | LCH   | applecore              | 3.2.0           | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
       | LCH   | jei                    | 4.15.0.293      | jei_1.12.2_4.15.0.293.jar                          | None                                     |
       | LCH   | appleskin              | 1.0.14          | AppleSkin-mc1.12-1.0.14.jar                        | None                                     |
       | LCH   | aquaculture            | 1.6.8           | Aquaculture-1.12.2-1.6.8.jar                       | None                                     |
       | LCH   | armourers_workshop     | 1.12.2-0.51.0   | Armourers-Workshop-1.12.2-0.51.0.jar               | None                                     |
       | LCH   | aroma1997core          | 2.0.0.0.b155    | Aroma1997Core-1.12.2-2.0.0.0.b155.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCH   | aromabackup            | 2.1.1.3.b103    | AromaBackup-1.12.2-2.1.1.3.b103.jar                | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCH   | aromabackuprecovery    | 2.1.1.3.b103    | AromaBackup-1.12.2-2.1.1.3.b103.jar                | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCH   | codechickenlib         | 3.2.3.358       | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCE   | brandonscore           | 2.4.19          | BrandonsCore-1.12.2-2.4.19.214-universal.jar       | None                                     |
       | LC    | cd4017be_lib           | 6.5.1           | CD4017BE_lib-1.12.2-6.5.1.jar                      | None                                     |
       | LC    | chunkpregenerator      | 2.5.0           | Chunk+Pregenerator-V1.12-2.5.0.jar                 | None                                     |
       | LC    | cofhcore               | 4.6.6           | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
       | LC    | cofhworld              | 1.4.0           | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
       | LC    | controlling            | 3.0.10          | Controlling-3.0.10.jar                             | None                                     |
       | LC    | crafttweaker           | 4.1.20          | crafttweaker2-1.12-4.1.20.636.jar                  | None                                     |
       | LC    | cookingforblockheads   | 6.4.71          | CookingForBlockheads_1.12.2-6.4.71.jar             | None                                     |
       | LC    | ctgui                  | 1.0.0           | crafttweaker2-1.12-4.1.20.636.jar                  | None                                     |
       | LC    | crafttweakerjei        | 2.0.3           | crafttweaker2-1.12-4.1.20.636.jar                  | None                                     |
       | LC    | dtm                    | 1.0             | DarkThemeMod-1.0.jar                               | None                                     |
       | LC    | thermalfoundation      | 2.6.7           | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
       | LC    | deepmoblearning        | 1.12.2-2.5.2    | deepmoblearning-1.12.2-2.5.2-universal.jar         | None                                     |
       | LC    | eleccore               | 1.9.453         | ElecCore-1.12.2-1.9.453.jar                        | None                                     |
       | LC    | mcjtylib_ng            | 3.5.4           | mcjtylib-1.12-3.5.4.jar                            | None                                     |
       | LC    | rftools                | 7.73            | rftools-1.12-7.73.jar                              | None                                     |
       | LC    | deepresonance          | 1.8.0           | deepresonance-1.12-1.8.0.jar                       | None                                     |
       | LC    | draconicevolution      | 2.3.25          | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
       | LC    | draconicadditions      | 1.16.3          | Draconic-Additions-1.12.2-1.16.3.43-universal.jar  | None                                     |
       | LC    | zerocore               | 1.12.2-0.1.2.9  | zerocore-1.12.2-0.1.2.9.jar                        | None                                     |
       | LC    | bigreactors            | 1.12.2-0.4.5.68 | ExtremeReactors-1.12.2-0.4.5.68.jar                | None                                     |
       | LC    | fluxnetworks           | 4.0.14          | fluxnetworks_1.12.2_4.0.14_31.jar                  | None                                     |
       | LC    | foamfix                | 0.10.11-1.12.2  | foamfix-0.10.11-1.12.2.jar                         | None                                     |
       | LC    | harvest                | 1.12-1.2.7-20   | harvest-1.12-1.2.7-20.jar                          | None                                     |
       | LC    | waila                  | 1.8.26          | Hwyla_1.8.26_B41_1.12.2.jar                        | None                                     |
       | LC    | oxygen_core            | 0.11.4          | oxygen-core-1.12.2-0.11.4.jar                      | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LC    | oxygen_teleportation   | 0.11.1          | oxygen-teleportation-1.12.2-0.11.1.jar             | bd38448c93e077d9ef82cf9509ae67b404862367 |
       | LC    | rs_ctr                 | 0.3.1           | RedstoneControl-1.12.2-0.3.1.3.jar                 | None                                     |
       | LC    | rftoolscontrol         | 2.0.2           | rftoolsctrl-1.12-2.0.2.jar                         | None                                     |
       | LC    | rftoolsdim             | 5.71            | rftoolsdim-1.12-5.71.jar                           | None                                     |
       | LC    | silentlib              | 2.2.18          | SilentLib-1.12-2.2.18-100.jar                      | None                                     |
       | LC    | scalinghealth          | 1.3.19          | ScalingHealth-1.12-1.3.19-102.jar                  | None                                     |
       | LC    | scannable              | 1.6.3.26        | Scannable-MC1.12.2-1.6.3.26.jar                    | None                                     |
       | LC    | thermalexpansion       | 5.5.7           | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
       | LC    | thermaldynamics        | 2.5.6           | thermaldynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |
       | LC    | thermalsolars          | 1.12.2 V1.9.5   | thermalsolars-1.12.2-1.9.5.jar                     | None                                     |
       | LC    | tombmanygraves         | @VERSION@       | TombManyGraves-1.12-4.0.3.jar                      | None                                     |
       | LC    | vanillafix             | 1.0.10-150      | VanillaFix-1.0.10-150.jar                          | None                                     |
       | LC    | vanillafoodpantry      | 4.3.1           | vanillafoodpantry-mc1.12.2-4.3.1.jar               | None                                     |
       | LC    | wct                    | 3.12.97         | WirelessCraftingTerminal-1.12.2-3.12.97.jar        | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LC    | worldselectionadvanced | 1.12.2-02       | WorldSelectionAdvanced-1.12.2-02.jar               | None                                     |
       | LC    | xaerominimap           | 21.7.0          | Xaeros_Minimap_21.7.0_Forge_1.12.jar               | None                                     |
       | LC    | xaeroworldmap          | 1.13.3          | XaerosWorldMap_1.13.3_Forge_1.12.jar               | None                                     |
       | LC    | xlfoodmod              | 1.12.2-1.9.2    | XL_Food_Mod_1.12.2_1.9.2.jar                       | None                                     |
       | LC    | solcarrot              | 1.8.4           | solcarrot-1.12.2-1.8.4.jar                         | None                                     |
       | LC    | eleccoreloader         | 1.9.453         | ElecCore-1.12.2-1.9.453.jar                        | None                                     |
  Loaded coremods (and transformers): XaeroMinimapPlugin (Xaeros_Minimap_21.7.0_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                        xaero.common.core.transformer.GuiIngameForgeTransformer
                                        xaero.common.core.transformer.GuiBossOverlayTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b155.jar)
                                        
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.13.3_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                      SHLoadingPlugin (ScalingHealth-1.12-1.3.19-102.jar)
                                        net.silentchaos512.scalinghealth.asm.SHClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.11-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CorePlugin (WorldSelectionAdvanced-1.12.2-02.jar)
                                        sedridor.worldselectionadvanced.core.Transformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13587 Compatibility Profile Context 19.40.50 26.20.14050.2' Renderer: 'AMD Radeon(TM) Vega 8 Graphics'
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  Suspected Mods: Draconic Additions (draconicadditions), Brandon's Core (brandonscore)
  Launched Version: 1.12.2-forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13587 Compatibility Profile Context 19.40.50 26.20.14050.2, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx

___________________________________________________________________
VanillaFix says that "Draconic Additions" and "Brandon's Core" are identified as potencial causes.
I downloaded the latest versions of both files.

**Comment by FoxMcloud5655** [comment]
Draconic Evolution is out of date.
