### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by Nagispace** [FoxMcloud5655/Draconic-Additions#44]
Project Inteligence can't download the initial manifest.json and it seems I can't fix the issue.
Is there any workarround to have the offline documentation ?

**Comment by FoxMcloud5655** [comment]
This would be a Project Intelligence issue, not a Draconic Additions issue.

Regardless, if you search for the repository "PIDocs" here on GitHub under the user "brandon3055", that contains all the documentation.  Download that as a .zip and extract it somewhere, go into the settings of Project Intelligence after opening it up in-game, and select "Edit Mode".  It will ask for the absolute path of the repository you just downloaded.  Put it in, and you'll have the documentation.

**Comment by SGZ-Creations** [comment]
ty

**Comment by SGZ-Creations** [comment]
could I get a specific .zip location ?


Or actually I would like an path example
