### ISSUE TITLE
How can i craft Hermal Armor from Draconic Additions?

### ISSUE THREAD

**Issue by Tamagoshi3dmax** [FoxMcloud5655/Draconic-Additions#45]
I have Draconic Additions...and i finally got how to craft Energized Potato Armor...but how can i get Hermal Potato Armor? I click to see the recipe with Jei...but it doesnt show anything. Even if i click in Hermal (rotten potato icon)...it doesnt show nothing. I dont know if it has the same problem as Mystical Agraddition with Insanium...that i had to add other mod to use Insanium...please somebody help me...im tired to get Hermal Armor from creative...i want to craft it...thanks.

**Comment by FoxMcloud5655** [comment]
Hermal Armor is only available in hard mode.  You must enable it in Draconic Evolution's settings.

**Comment by Tamagoshi3dmax** [comment]
How can i enable hard mode? Is it in config file from Draconic Evolution?

**Comment by FoxMcloud5655** [comment]
Yes.  I just said it was in DE's settings :P

**Comment by Tamagoshi3dmax** [comment]
Nice...i'll try it later...thanks a lot
