### ISSUE TITLE
Minecraft crash report

### ISSUE THREAD

**Issue by Ronald0410** [FoxMcloud5655/Draconic-Additions#46]
After I install this mod, Minecraft is raising an error: 

Error: java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo
Exit Code: -1

When I delete this mod the error no longer exists. Here is the full crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LucraftCoreCoreMod (lucraftcore-1-12-2-2-4-14.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.9-core.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  PerformantLoadingPlugin (performant-1.12.2-1.10.jar)
  BetterSprintingCore (BetterSprinting-1.12.2-v2.1.2.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 9/1/21 2:48 PM
Description: Initializing game

java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo
	at lucraft.mods.lucraftcore.LCConfig$Materials.<init>(LCConfig.java:108)
	at lucraft.mods.lucraftcore.LCConfig.<clinit>(LCConfig.java:36)
	at lucraft.mods.lucraftcore.addonpacks.AddonPackHandler.getAddonPacksDir(AddonPackHandler.java:61)
	at lucraft.mods.lucraftcore.core.LCClientHooks.insertAddonPackResourcePacks(LCClientHooks.java:37)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:789)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: slimeknights.tconstruct.library.client.MaterialRenderInfo
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at lucraft.mods.lucraftcore.LCConfig$Materials.<init>(LCConfig.java:108)
	at lucraft.mods.lucraftcore.LCConfig.<clinit>(LCConfig.java:36)
	at lucraft.mods.lucraftcore.addonpacks.AddonPackHandler.getAddonPacksDir(AddonPackHandler.java:61)
	at lucraft.mods.lucraftcore.core.LCClientHooks.insertAddonPackResourcePacks(LCClientHooks.java:37)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:789)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 375235720 bytes (357 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                              | Version                  | Source                                             | Signature                                |
	|:----- |:------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| L     | minecraft                       | 1.12.2                   | minecraft.jar                                      | None                                     |
	| L     | mcp                             | 9.42                     | minecraft.jar                                      | None                                     |
	| L     | FML                             | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | forge                           | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | foamfixcore                     | 7.7.4                    | minecraft.jar                                      | None                                     |
	| L     | damageindicatorsmod             | 1.0                      | [1.12.2]DamageIndicatorsMod-3.5.1.jar              | None                                     |
	| L     | appliedenergistics2             | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | None                                     |
	| L     | armoryexpansion                 | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
	| L     | armoryexpansion-conarm          | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
	| L     | armoryexpansion-custommaterials | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
	| L     | armoryexpansion-iceandfire      | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
	| L     | armoryexpansion-matteroverdrive | 1.4.2                    | armoryexpansion-1.4.2.jar                          | None                                     |
	| L     | avaritia                        | 3.3.0                    | avaritia-1-12-2-3-3-0-37-universal.jar             | None                                     |
	| L     | bettersprinting                 | 2.1.2                    | BetterSprinting-1.12.2-v2.1.2.jar                  | None                                     |
	| L     | bookshelf                       | 2.3.589                  | Bookshelf-1.12.2-2.3.589.jar                       | None                                     |
	| L     | brandonscore                    | 2.4.19                   | BrandonsCore-1.12.2-2.4.19.214-universal.jar       | None                                     |
	| L     | codechickenlib                  | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | None                                     |
	| L     | cofhcore                        | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| L     | cofhworld                       | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| L     | conarm                          | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                         | None                                     |
	| L     | creepypastacraft                | 2                        | CreepyPastaCraft_Reborn_V2c-1.12.2-hotfix1.jar     | None                                     |
	| L     | divinerpg                       | 1.7.1                    | DivineRPG-1.7.1.jar                                | None                                     |
	| L     | draconicadditions               | 1.14.1                   | Draconic-Additions-1.12.2-1.14.1.37-universal.jar  | None                                     |
	| L     | draconicevolution               | 2.3.27                   | Draconic-Evolution-1.12.2-2.3.27.353-universal.jar | None                                     |
	| L     | eplus                           | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                  | None                                     |
	| L     | fastleafdecay                   | v14                      | FastLeafDecay-v14.jar                              | None                                     |
	| L     | foamfix                         | 0.10.14-1.12.2           | foamfix-0.10.14-1.12.2.jar                         | None                                     |
	| L     | heroesexpansion                 | 1.12.2-1.3.5             | HeroesExpansion-1.12.2-1.3.5.jar                   | None                                     |
	| L     | waila                           | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| L     | ichunutil                       | 7.2.2                    | iChunUtil-1.12.2-7.2.2 (1).jar                     | None                                     |
	| L     | infinity                        | 1.12                     | infinity-1-12.jar                                  | None                                     |
	| L     | inventorypets                   | 2.0.15                   | inventorypets-1.12-2.0.15.jar                      | None                                     |
	| L     | jei                             | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| L     | journeymap                      | 1.12.2-5.7.0             | journeymap-1.12.2-5.7.0.jar                        | None                                     |
	| L     | lucraftcore                     | 1.12.2-2.4.14            | lucraftcore-1-12-2-2-4-14.jar                      | None                                     |
	| L     | magicalcrops                    | 1.0.1                    | Magical-Crops-Mod-1.12.2.jar                       | None                                     |
	| L     | mantle                          | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| L     | metallurgy                      | 1.2.7                    | Metallurgy-4-Reforged-1.2.7.jar                    | None                                     |
	| L     | moartinkers                     | 0.6.0                    | moartinkers-0.6.0.jar                              | None                                     |
	| L     | morph                           | 7.2.0                    | Morph-1.12.2-7.2.1 (1).jar                         | None                                     |
	| L     | netherendingores                | 1.12.2-1.3               | Netherending-Ores-1.12.2-1.3.jar                   | None                                     |
	| L     | performant                      | 1.12.2-1.4               | performant-1.12.2-1.10.jar                         | None                                     |
	| L     | projecte                        | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| L     | redstoneflux                    | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| L     | scp                             | 2.4.0                    | SCP_Lockdown-1.12.2-2.4.0-hotfix.jar               | None                                     |
	| L     | simplemagnets                   | 1.0.5                    | simplemagnets-1.0.5-mc1.12.jar                     | None                                     |
	| L     | somanyenchantments              | 0.5.0                    | SoManyEnchantments-0.5.0.jar                       | None                                     |
	| L     | speedsterheroes                 | 1.12.2-2.2.1             | speedsterheroes-1-12-2-2-2-1.jar                   | None                                     |
	| L     | srparasites                     | 1.9.0                    | SRParasites-1.12.2v1.9.0ALPHA14.jar                | None                                     |
	| L     | tconstruct                      | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| L     | the-fifth-world                 | 0.5                      | the-fifth-world-0-5-1.jar                          | None                                     |
	| L     | thermalfoundation               | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| L     | tinker_io                       | rw2.8.3                  | tinker_io-1.12.2-rw2.8.3.jar                       | None                                     |
	| L     | tinkersaddons                   | 1.0.7                    | Tinkers-Addons-Mod-1.12.2.jar                      | None                                     |
	| L     | tinkersjei                      | 1.2                      | tinkersjei-1.2.jar                                 | None                                     |
	| L     | tinkertoolleveling              | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| L     | veinminer                       | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
	| L     | veinminermodsupport             | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
	| L     | thebetweenlands                 | 3.4.9                    | thebetweenlands-3-4-9-universal.jar                | None                                     |

	Loaded coremods (and transformers): 
LucraftCoreCoreMod (lucraftcore-1-12-2-2-4-14.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.9-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
PerformantLoadingPlugin (performant-1.12.2-1.10.jar)
  
BetterSprintingCore (BetterSprinting-1.12.2-v2.1.2.jar)
  chylex.bettersprinting.system.core.TransformerEntityPlayerSP
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 451.67' Renderer: 'GeForce GTX 1060 with Max-Q Design/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz

**Comment by FoxMcloud5655** [comment]
This is an issue with LUCraft.  We've already asked them to fix it, so I highly suggest updating that mod (and all other mods).

Unfortunately, if they have not fixed this, you're out of luck and will have to get rid of LUCraft or Draconic Evolution/Additions.
