### ISSUE TITLE
Add Chaotic Energy Crystals

### ISSUE THREAD

**Issue by WaitingIdly** [FoxMcloud5655/Draconic-Additions#47]
Draconic Evolution adds the first 3 tiers of Energy Crystals (Basic, Wyvern, and Draconic) for the 3 types of Energy Crystals (I/O, Relay, and Wireless Energy). Draconic Additions should add a Chaotic tier for each of the three types. 
[Link to the Energy Crystal code for 1.12.2 Draconic Evolution](https://github.com/brandon3055/Draconic-Evolution/blob/1.12.2/src/main/java/com/brandon3055/draconicevolution/blocks/energynet/EnergyCrystal.java)

**Comment by FoxMcloud5655** [comment]
I have rejected this idea numerous times on the grounds that it is simply not necessary.  If you can show me a real world instance of a non-troll modpack that is actually limited by the speeds of a Draconic I/O Crystal, I will consider making them.
