### ISSUE TITLE
Chaotic bow draconic fire arrow

### ISSUE THREAD

**Issue by ghost** [FoxMcloud5655/Draconic-Additions#48]
Where can i turn it off in config file? i can't find it.(or am I blind)

**Comment by FoxMcloud5655** [comment]
Due to the sheer amount of energy required, normal arrows are disintegrated when attempted to be fired with this weapon.  You cannot turn this option off.

I'll be reducing the RF cost in a later update thanks to how the Chaotic Bow is implementated in DE3.
