### ISSUE TITLE
Chaotic armor Flight speed

### ISSUE THREAD

**Issue by Aphenon** [FoxMcloud5655/Draconic-Additions#5]
The flight speed modifier on the chaotic chestplate is locked on 600%
![image](https://user-images.githubusercontent.com/9679372/56914868-808f2380-6ab5-11e9-97b3-5fcdeae9e940.png)
600%+ can be nice. but not allowing less than 600% is a complete turnoff =\ disregard this if that is not intended :)

**Comment by FoxMcloud5655** [comment]
This is 100% intended.  Please look at the Project Intelligence documentation in-game for information on how to unlock it.
