### ISSUE TITLE
infinite item duplication using harnesses (1.16.5)

### ISSUE THREAD

**Issue by NyanMC** [FoxMcloud5655/Draconic-Additions#54]
forge version: 36.2.34

mods used: 
BrandonsCore-1.16.5-3.0.15.248-universal.jar
CodeChickenLib-1.16.5-4.0.7.445-universal.jar
curios-forge-1.16.5-4.0.8.2.jar
Draconic-Additions-1.16.5-2.2.2.5-universal.jar
Draconic-Evolution-1.16.5-3.0.27.462-universal.jar
and jei but i did not mark the version of jei used (edit: jei-1.16.5-7.7.1.152.jar)

steps to reproduce:
get a tile entity which holds items (i tested this with a furnace's item and fuel slot, have not tested other tile entities)
place the tile entity down and put some items in it
equip any harness
place the tile entity in the harness

result:
items in the harness' tile entity will be dropped on your player endlessly until you place the tile entity back down, where they will still be in the tile entity

(hopefully) an attached video: https://user-images.githubusercontent.com/44331238/181115214-0e922fa3-6db2-467f-b6b9-9781e3cd739d.mp4

(not shown in the video: i placed one coal in the furnace's fuel slot)

**Comment by FoxMcloud5655** [comment]
I thought I fixed this bug during development...  Guess it shows it's ugly head again.
