### ISSUE TITLE
[1.18] How to play? Since Draconic Evolution is still on 1.16.5 !

### ISSUE THREAD

**Issue by SigmaFlame** [FoxMcloud5655/Draconic-Additions#57]
Hello,

How to get this mod on 1.18.2 ?
Since Draconic Evolution is still on 1.16.5 !
And the description clearly indicates that Draconic Evolution is required.

Is there an hidden version somewhere ?
Thank in advance.

**Comment by FoxMcloud5655** [comment]
Draconic Evolution is currently in closed beta testing and will come out at a later point, likely sometime this month.

**Comment by FoxMcloud5655** [comment]
It's currently out now.
