### ISSUE TITLE
Russian localization not working

### ISSUE THREAD

**Issue by ydika** [FoxMcloud5655/Draconic-Additions#58]
Russian localization not working.
[Draconic-Additions-1.12.2-1.17.0.45-universal](https://www.curseforge.com/minecraft/mc-mods/draconicadditions/files/3514704)

I am attaching the corrected and supplemented localization file.
[ru_RU.zip](https://github.com/FoxMcloud5655/Draconic-Additions/files/10743000/ru_RU.zip)

**Comment by FoxMcloud5655** [comment]
Did this get completed and I just forgot about it, or is it still broken?

**Comment by ydika** [comment]
Localization is still broken
[Draconic-Additions-1.12.2-1.17.0.45-universal](https://www.curseforge.com/minecraft/mc-mods/draconicadditions/files/3514704)
