### ISSUE TITLE
Infused potato armor in 1.16.5 

### ISSUE THREAD

**Issue by Danield1363** [FoxMcloud5655/Draconic-Additions#59]
Only potato armor inert is available. Is there anything I can do?
![Base Profile Screenshot 2023 04 28 - 05 20 44 80](https://user-images.githubusercontent.com/132052051/235094784-ec950d6c-d70b-418c-8ff9-21834aa6b223.png)

**Comment by FoxMcloud5655** [comment]
Not implemented.
