### ISSUE TITLE
Mod Id duplication

### ISSUE THREAD

**Issue by Krollbotid** [FoxMcloud5655/Draconic-Additions#60]
![image](https://github.com/FoxMcloud5655/Draconic-Additions/assets/37172495/dfd6903d-c37a-4575-8598-9f36bc36ff8d)
both are installed through curseforge launcher and are latest version from there

**Comment by FoxMcloud5655** [comment]
This is not an issue with Draconic Additions.  Right there, you see that "Project Intelligence" is being labeled as the modid "draconicadditions".

This means it's a bad download.  Go get Project Intelligence again.
