### ISSUE TITLE
Server crash during stabilization ritual

### ISSUE THREAD

**Issue by SkippyMitch** [FoxMcloud5655/Draconic-Additions#9]
During the ritual of stabilization a player on my server reported a forced restart of the server.
The item got stuck on the outside of the core for around 10 seconds, then crash. Upon restart of the server the ritual was successful. 

crash report
https://gist.github.com/SkippyMitch/ab3c1b4b0c70da1ffccbd76a522a2e86

if you need more info I'll be happy to help!

**Comment by FoxMcloud5655** [comment]
At first glance through the crash report and the situation of your crash combined with looking through the relevant code, I see nothing about what I'm doing that could have caused this crash.

It appears as though this is the fault of something located at 819,63,816.  Mind telling me what's at those coords?

**Comment by SkippyMitch** [comment]
Weird, that's the spawn cords, but about 9 blocks below the surface. I guess OTG could be to blame.
